custom_file_path: ./specific_config.yaml
devices:
  - mac: any_mac_address
    name: any_device_name
    moisture:
      check: true
      high: 100
      low: 10
    fertility:
      check: true
      high: 100000
      low: 0
    light:
      check: false
      high: 30000
      low: 1000
    temp:
      check: false
      high: 30
      low: 5
    battery:
      check: true
      high: 100
      low: 15
