log_level: INFO
custom_file_path: ./specific_config.yaml
smtp_info:
  apikey: YOUR_MAILJET_APIKEY
  apisecret: YOUR_MAILJET_APISECRET
  sender_mail: sender@domain.com
  sender_name: sender name
mail_info:
  to: mailto@domain.com
  cc:
  bcc:
  subject: "[WARN] Plants Manager: You have to water your plants"
devices:
  - mac: any_mac_address
    name: any_device_name
    moisture:
      check: true
      high: 100
      low: 10
    fertility:
      check: true
      high: 100000
      low: 0
    light:
      check: false
      high: 30000
      low: 1000
    temp:
      check: false
      high: 30
      low: 5
    battery:
      check: true
      high: 100
      low: 15
